include .env

# Путь до папки с миграциями
MIGRATIONS_PATH=./migrations

# Команда для миграции вверх
pg-migrate:
	migrate -path $(MIGRATIONS_PATH) -database "$(STORAGE_PATH)" up

pg-down:
	migrate -path $(MIGRATIONS_PATH) -database "$(STORAGE_PATH)" down

server-run:
	go run cmd/main.go --config=.env